# Generated by Django 2.2.5 on 2019-10-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0039_wastenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworknotification',
            name='production_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine'),
        ),
        migrations.AddField(
            model_name='reworknotification',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
        migrations.AddField(
            model_name='stopnotification',
            name='production_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine'),
        ),
        migrations.AddField(
            model_name='stopnotification',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
        migrations.AddField(
            model_name='wastenotification',
            name='production_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_service.ProductionLine'),
        ),
        migrations.AddField(
            model_name='wastenotification',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_service.ProductionOrder'),
        ),
    ]
