# Generated by Django 2.2.5 on 2019-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_service', '0040_auto_20191003_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reworknotification',
            name='segmented_quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stopnotification',
            name='segmented_quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wastenotification',
            name='segmented_quantity',
            field=models.CharField(max_length=100),
        ),
    ]
