# Generated by Django 2.2.5 on 2019-09-26 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='Group_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
